### PR TITLE
Change from cookie to header based auth for vSphere REST APIs

### LINKED ISSUE #87: requests.cookies.CookieConflictError: There are multiple cookies with name, 'vmware-api-session-id'
As previously seen in #83 I have been getting the error "There are multiple cookies with name, 'vmware-api-session-id'" with a new install of StackStorm 3.5 on CentOS 7.9

In debugging this I discovered [VMware KB 78315](https://kb.vmware.com/s/article/78315) that states cookie based authentication to the vSphere REST APIs is deprecated.

I have tested (and will submit a PR) moving to header based authentication for the REST API and it resolves the issue mentioned aboev also.

### PR DESCRIPTION
**Pull request by dsbibby**
Cookie based authentication is deprecated - see [VMware KB 78315](https://kb.vmware.com/s/article/78315)

This PR changes to use header based authentication instead an in doing so addresses #83 and fixes #87

### CODE REVIEW

**Review by bishopbm1 — CHANGES_REQUESTED** [review]
Thank you for the PR! 

Will you please update and add some tests to https://github.com/StackStorm-Exchange/stackstorm-vsphere/blob/master/tests/test_action_vmwarelib_tagging.py for the changes.

Also please add a section to the Change log and update the version in the pack.yaml

Thank you!

**Comment by bishopbm1** [comment]
We had another company confirm and test for vsphere 7 and we testing on vsphere 6 and everything is working as expected. Ready to merge as soon as unit tests and other items are added.

**Comment by dsbibby** [comment]
Hi, I've been having a look at the existing tests trying to get my head around them. Any pointers/tips greatly received!

The only thought I had so far about this is that unless I'm missing something, it looks like there is no test for the login method at present. As such should the unit tests really be raised under a separate PR to validate the current code behavior. Then this PR could be validated using those tests?

Also, could consider using [vcsim](https://github.com/vmware/govmomi/tree/master/vcsim) as part of the unit testing? I'm not sure if it would fit in to the current test framework or not.

**Comment by dsbibby** [comment]
Hi, I've been having a look at the existing tests trying to get my head around them. Any pointers/tips greatly received!

The only thought I had so far about this is that unless I'm missing something, it looks like there is no test for the login method at present. As such should the unit tests really be raised under a separate PR to validate the current code behavior. Then this PR could be validated using those tests?

Also, could consider using [vcsim](https://github.com/vmware/govmomi/tree/master/vcsim) as part of the unit testing? I'm not sure if it would fit in to the current test framework or not.

**Comment by bishopbm1** [comment]
@dsbibby I added a test for the login method. You are correct that there were not tests on it originally. I had to make an update to fix the CircleCi workflow but we have switched this pack to GitHub Actions. I will be switching that back and updating the ChangeLog and Pack yaml so that we can get this merged.

Please review the changes that I made to the PR and let me know if you have any questions about the changes that I made or would like me to explain anything further. I am in the StackStorm Slack channel also if that is easier!

**Review by bishopbm1 — APPROVED** [review]
LGTM

**Pull request merged**
