### PR TITLE
action: shutdown guest

### PR DESCRIPTION
**Pull request by jeking3**
This action initiates VirtualMachine.ShutdownGuest() which is not a task and has no response.  It initiates an orderly guest shutdown but does not wait for the shutdown to complete.  If runtime.powerState is not "poweredOff" this will likely raise an exception (based on the VMware documentation).  One can monitor the runtime.powerState changing to "poweredOff" to wait for the state change.

I also added an easier way to mock a single VM (by MOID) in the tests.
100% code coverage.

### CODE REVIEW

**Review by nmaludy — APPROVED** [review]
LGTM

**Comment by jeking3** [comment]
I'm also looking for tips on how I could pause a workflow and have a sensor update (monitoring the VM for changes like the runtime.powerState state change) resume the workflow. :)

**Comment by nmaludy** [comment]
@jeking3 i think this is the wrong approach (most of the time).

Usually you would want to write a Sensor that listens for events and emits triggers. You would then write a rule to match those triggers and invoke an action.

You could also write an Action that does the polling internally.

**Comment by jeking3** [comment]
The action that I invoke could resume a workflow (and perhaps set a variable on the workflow before resuming it)?  I think that's better design than blocking a runner with a potentially long-running busy wait loop.

**Comment by LindsayHill** [comment]
@jeking3 if you can resolve the conflicts here, this should be OK for merging too

**Comment by jeking3** [comment]
@LindsayHill all set

**Pull request merged**
