### PR TITLE
add missing file guest_process_run.yaml in workflows

### LINKED ISSUE #42: The ../actions/workflows/guest_process_run.yaml file is referenced but is not included in the repo
there is a file `../actions/guest_process_run.yaml` but no equivalent in `../actions/workflows`.

This results in errors from running vsphere commands such as `vsphere.guest_process_run`:

```json
{
  "traceback": "  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/container/base.py\", line 127, in _do_run\n    (status, result, context) = runner.run(action_params)\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/orquesta_runner/orquesta_runner.py\", line 85, in run\n    wf_def = self.get_workflow_definition(self.entry_point)\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/orquesta_runner/orquesta_runner.py\", line 50, in get_workflow_definition\n    with open(entry_point, 'r') as def_file:\n",
  "error": "[Errno 2] No such file or directory: u'/opt/stackstorm/packs/vsphere/actions/workflows/guest_process_run.yaml'"
}
```

### PR DESCRIPTION
**Pull request by jeking3**
I quickly put this together put I haven't had time to test it.  
Any chance someone who wants to use it could give it a try?

This fixes #42

### CODE REVIEW

**Review by arm4b — CHANGES_REQUESTED** [review]
Thanks for quick reaction fixing #42! :+1: 

Let's please add a Changelog record and bump a version in `pack.yaml`.

**Comment by arm4b** [comment]
@dustinupdyke can you please help running the workflow you previously reported to be missing?

**Comment by jeking3** [comment]
I just ran this and it works now:
```
root@7d5ddc98fb1c:/# st2 run vsphere.guest_process_run username=Administrator command="CMD.EXE" arguments="/C DIR C:\\" password=***** vm_id=vm-1734
........
id: 5c65d60db9f03b011071a7af
action.ref: vsphere.guest_process_run
parameters:
  arguments: /C DIR C:  command: CMD.EXE
  password: '********'
  username: Administrator
  vm_id: vm-1734
status: succeeded
start_timestamp: Thu, 14 Feb 2019 20:56:45 UTC
end_timestamp: Thu, 14 Feb 2019 20:56:59 UTC
result:
  output:
    exit_code: 0
    stderr: ''
    stdout: " Volume in drive C has no label.
 Volume Serial Number is 8CC1-FFE5

 Directory of C:\

07/16/2016  08:23 AM    <DIR>          PerfLogs
09/24/2018  02:06 PM    <DIR>          Program Files
07/16/2016  08:23 AM    <DIR>          Program Files (x86)
09/24/2018  08:44 PM    <DIR>          Users
11/14/2018  12:42 PM    <DIR>          Windows
               0 File(s)              0 bytes
               5 Dir(s)   7,128,453,120 bytes free
"
+--------------------------+------------------------+---------------+----------------------------+------------------------------+
| id                       | status                 | task          | action                     | start_timestamp              |
+--------------------------+------------------------+---------------+----------------------------+------------------------------+
| 5c65d60eb9f03b003559c7f7 | succeeded (2s elapsed) | dir_create    | vsphere.guest_dir_create   | Thu, 14 Feb 2019 20:56:46    |
|                          |                        |               |                            | UTC                          |
| 5c65d610b9f03b003559c7fa | succeeded (2s elapsed) | process_start | vsphere.guest_process_star | Thu, 14 Feb 2019 20:56:48    |
|                          |                        |               | t                          | UTC                          |
| 5c65d613b9f03b003559c7fd | succeeded (2s elapsed) | process_wait  | vsphere.guest_process_wait | Thu, 14 Feb 2019 20:56:50    |
|                          |                        |               |                            | UTC                          |
| 5c65d615b9f03b003559c800 | succeeded (2s elapsed) | get_stdout    | vsphere.guest_file_read    | Thu, 14 Feb 2019 20:56:53    |
|                          |                        |               |                            | UTC                          |
| 5c65d617b9f03b003559c803 | succeeded (2s elapsed) | get_stderr    | vsphere.guest_file_read    | Thu, 14 Feb 2019 20:56:55    |
|                          |                        |               |                            | UTC                          |
| 5c65d61ab9f03b003559c806 | succeeded (1s elapsed) | dir_delete__2 | vsphere.guest_dir_delete   | Thu, 14 Feb 2019 20:56:58    |
|                          |                        |               |                            | UTC                          |
+--------------------------+------------------------+---------------+----------------------------+------------------------------+
root@7d5ddc98fb1c:/# exit
```

**Review by arm4b — APPROVED** [review]
Looks awesome, thanks! :+1:

**Pull request merged**
